### ISSUE TITLE
upgrade doesn't works in stable channel

### ISSUE THREAD

**Issue by jalberto** [docker/for-azure#34]
### Expected behavior

upgrade docker to latest stable version

### Actual behavior

still in previous version

### Information

Just created swarm
run `docker run \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /usr/bin/docker:/usr/bin/docker \
  -ti \
  docker4x/upgrade-azure:17.06.1-ce-azure1`

The whole process seems to go without errors, 2 of 3 nodes get restarted (the one running upgrade never got restarted)

after the process still in 17.06.0 version

### Steps to reproduce the behavior

  1. run upgrade container
  2. run version

**Comment by ddebroy** [comment]
Which version were you upgrading from? Can you send the `docker-diagnose` output from the swarm in the above state please? 

Also can you check the deployment status in Azure Portal for the resource group and see if it happens to be in a `Failed` state. If so, can you check and report any details of the failure?

**Comment by jalberto** [comment]
- Upgrading from 17.06.0
- No failed status in azure portal
- diagnose:

```
OK hostname=swarm-manager000000 session=1505154821-m9S0xjab0lBrw2nvv3RPzpZULXCUhn3D
OK hostname=swarm-manager000001 session=1505154821-m9S0xjab0lBrw2nvv3RPzpZULXCUhn3D
OK hostname=swarm-manager000002 session=1505154821-m9S0xjab0lBrw2nvv3RPzpZULXCUhn3D
OK hostname=swarm-worker000000 session=1505154821-m9S0xjab0lBrw2nvv3RPzpZULXCUhn3D
Done requesting diagnostics.
Your diagnostics session ID is 1505154821-m9S0xjab0lBrw2nvv3RPzpZULXCUhn3D
Please provide this session ID to the maintainer debugging your issue.
```

**Comment by ddebroy** [comment]
Did you make modifications to the template, deploy it and then tried to upgrade from the custom template using `upgrade-azure:17.06.1-ce-azure1`?

**Comment by jalberto** [comment]
yes, I see where are you going. I changed the VMs size

**Comment by ddebroy** [comment]
Right .. I see from the logs that `Standard_D2S_v3` was passed and most likely that led to issues with Azure not being able to map that to the parameters in the new template. I tried your scenario with the same config and upgraded and it seemed to work. The stable download endpoint [https://download.docker.com/azure/stable/Docker.tmpl] has now been updated to 17.06.1 - so that should serve your purpose for now.

**Comment by jalberto** [comment]
Thanks @ddebroy 

So any modification in the template can make the upgrade to fail. 

- is not latest stable version 17.06.2? is D4A updated as often as other distributions?
- it is possible to crate workers with different sizes? How wlil upgrade works then?

Thanks in advance

**Comment by ddebroy** [comment]
Hi @jalberto The update for D4A takes a little while longer since it takes a while to get the VHDs (with the latest Docker engine) published in the Azure marketplace which needs to go through a certification process. The 17.06.2 VHD is going through that process right now.

Regarding workers with different sizes, can you clarify? Since the worker instances are part of the same VMSS, they all need to be the same size (i.e. that of the VMSS).

**Comment by jalberto** [comment]
Thanks for your time.

About VMs sizes I am interested in have a mix of machines for different
tasks, or even environments (production & staging)

They simplest way would be to create several VMSS (eg: high CPU, high men)
then based on labels swarm can decide which VM is better for a service
